# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ff24ec704ceb5a56b107f3028538e3eba02baadb70f9a71d4dba6ad32ac0b7d8eefbe04d0456b852ea0285b4ead9d1063825598370a47c301586965268c9c47

test:
  secret_key_base: 0589129f60efe6c8fda5299f1009b121a7ea3244a10c60b1121ff7a2f61b85893f31ed0819f4159e8a5c63d2d41e1135d9903dd92432a07a67b21c862645cbc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
